// auth
export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

//login
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//autoLogin
export const AUTO_LOGIN = "AUTO_LOGIN";
export const AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS";
export const AUTO_LOGIN_FAILURE = "AUTO_LOGIN_FAILURE";


//entrepreneur
export const LOGOUT = "LOGOUT";
export const DELETE_ENTREPRENEUR = "DELETE_ENTREPRENEUR";
export const DELETE_ENTREPRENEUR_SUCCESS = "DELETE_ENTREPRENEUR_SUCCESS";
export const DELETE_ENTREPRENEUR_FAILURE = "DELETE_ENTREPRENEUR_FAILURE";

export const MODIFY_PASSWORD = "MODIFY_PASSWORD";
export const MODIFY_PASSWORD_SUCCESS = "MODIFY_PASSWORD_SUCCESS";
export const MODIFY_PASSWORD_FAILURE = "MODIFY_PASSWORD_FAILURE";


