// auth
export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";



//login
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//autoLogin
export const AUTO_LOGIN = "AUTO_LOGIN";
export const AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS";
export const AUTO_LOGIN_FAILURE = "AUTO_LOGIN_FAILURE";


//entrepreneur
export const LOGOUT = "LOGOUT";
export const DELETE_ENTREPRENEUR = "DELETE_ENTREPRENEUR";
export const DELETE_ENTREPRENEUR_SUCCESS = "DELETE_ENTREPRENEUR_SUCCESS";
export const DELETE_ENTREPRENEUR_FAILURE = "DELETE_ENTREPRENEUR_FAILURE";

export const MODIFY_PASSWORD = "MODIFY_PASSWORD";
export const MODIFY_PASSWORD_SUCCESS = "MODIFY_PASSWORD_SUCCESS";
export const MODIFY_PASSWORD_FAILURE = "MODIFY_PASSWORD_FAILURE";


//api
export const API_CHECK_ENTREPRENEUR_STATUS = "API_CHECK_ENTREPRENEUR_STATUS";
export const API_CHECK_ENTREPRENEUR_STATUS_SUCCESS = "API_CHECK_ENTREPRENEUR_STATUS_SUCCESS";
export const API_CHECK_ENTREPRENEUR_STATUS_FAILURE = "API_CHECK_ENTREPRENEUR_STATUS_FAILURE";

export const API_CHECK_ENTREPRENEUR_VAILDATE = "API_CHECK_ENTREPRENEUR_VAILDATE";
export const API_CHECK_ENTREPRENEUR_VAILDATE_SUCCESS = "API_CHECK_ENTREPRENEUR_VAILDATE_SUCCESS";
export const API_CHECK_ENTREPRENEUR_VAILDATE_FAILURE = "API_CHECK_ENTREPRENEUR_VAILDATE_FAILURE";

export const API_REQUEST = "API_REQUEST";

export const NOT_ENTREPRENEUR_NUMBER = "국세청에 등록되지 않은 사업자등록번호입니다.";
